# Useful Tables

EggPaul = "🥚"
Caterpillars = "🐛🐛🐛"
Rule21Strong = "🏋️‍♂️🏋️‍♂️🏋️‍♂️"

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
moon_phases = ["🌑", "🌒", "🌓", "🌔", "🌕", "🌖", "🌗", "🌘"]
periodic_table = {
    1: 'H',
    2: 'He',
    3: 'Li',
    4: 'Be',
    5: 'B',
    6: 'C',
    7: 'N',
    8: 'O',
    9: 'F',
    10: 'Ne',
    11: 'Na',
    12: 'Mg',
    13: 'Al',
    14: 'Si',
    15: 'P',
    16: 'S',
    17: 'Cl',
    18: 'Ar',
    19: 'K',
    20: 'Ca',
    21: 'Sc',
    22: 'Ti',
    23: 'V',
    24: 'Cr',
    25: 'Mn',
    26: 'Fe',
    27: 'Co',
    28: 'Ni',
    29: 'Cu',
    30: 'Zn',
    31: 'Ga',
    32: 'Ge',
    33: 'As',
    34: 'Se',
    35: 'Br',
    36: 'Kr',
    37: 'Rb',
    38: 'Sr',
    39: 'Y',
    40: 'Zr',
    41: 'Nb',
    42: 'Mo',
    43: 'Tc',
    44: 'Ru',
    45: 'Rh',
    46: 'Pd',
    47: 'Ag',
    48: 'Cd',
    49: 'In',
    50: 'Sn',
    51: 'Sb',
    52: 'Te',
    53: 'I',
    54: 'Xe',
    55: 'Cs',
    56: 'Ba',
    57: 'La',
    58: 'Ce',
    59: 'Pr',
    60: 'Nd',
    61: 'Pm',
    62: 'Sm',
    63: 'Eu',
    64: 'Gd',
    65: 'Tb',
    66: 'Dy',
    67: 'Ho',
    68: 'Er',
    69: 'Tm',
    70: 'Yb',
    71: 'Lu',
    72: 'Hf',
    73: 'Ta',
    74: 'W',
    75: 'Re',
    76: 'Os',
    77: 'Ir',
    78: 'Pt',
    79: 'Au',
    80: 'Hg',
    81: 'Tl',
    82: 'Pb',
    83: 'Bi',
    84: 'Po',
    85: 'At',
    86: 'Rn',
    87: 'Fr',
    88: 'Ra',
    89: 'Ac',
    90: 'Th',
    91: 'Pa',
    92: 'U',
    93: 'Np',
    94: 'Pu',
    95: 'Am',
    96: 'Cm',
    97: 'Bk',
    98: 'Cf',
    99: 'Es',
    100: 'Fm',
    101: 'Md',
    102: 'No',
    103: 'Lr',
    104: 'Rf',
    105: 'Db',
    106: 'Sg',
    107: 'Bh',
    108: 'Hs',
    109: 'Mt',
    110: 'Ds',
    111: 'Rg',
    112: 'Cn',
    113: 'Nh',
    114: 'Fl',
    115: 'Mc',
    116: 'Lv',
    117: 'Ts',
    118: 'Og'
}

rules_info = {
    1: "Your password must be at least five characters",
    2: "Your password must include a number",
    3: "Your password must include an uppercase letter",
    4: "Your password must include a special character",
    5: "The digits in your password must add up to 25",
    6: "Your password must include a month of the year",
    7: "Your password must include a Roman numeral",
    8: "Your password must include one of our sponsors",
    9: "The Roman numerals in your password should multiply to 35",
    10: "Your password must include this CAPTCHA",
    11: "Your password must include today’s Wordle answer,\nLook at the [link=https://github.com/imhlq/WordleCrasher]Wordle Crasher[/link] for help",
    12: "Your password must include a two letter symbol from the periodic table",
    13: "Your password must include the current phase of the moon as an emoji",
    14: "Your password must include the name of this country,\nLook at the [link=https://images.google.com/]Reversed Image Search[/link] for help",
    15: "Your password must include a leap year",
    16: "Your password must include the best move in algebraic chess notation,\nLook at the [link=https://nextchessmove.com/]Next Chess Move[/link] for help",
    17: "🥚 This is my chicken Paul. He hasn’t hatched yet. Please put him in your password and keep him safe",
    18: "The elements in your password must have atomic numbers that add up to 200",
    19: "All the vowels in your password must be bolded",
    20: "Oh no! Your password is on fire 🔥. Quick, put it out!",
    21: "Your password is not strong enough 🏋️‍♂️",
    22: "Your password must contain one of the following affirmations: I am loved | I am worthy | I am enough",
    23: "Paul has hatched ! Please don’t forget to feed him. He eats three 🐛 every minute",
    24: "Your password must include the URL of a YouTube video of this exact length",
    25: "A sacrifice must be made. Pick two letters that you will no longer be able to use",
    26: "Your password must contain twice as many italic characters as bold",
    27: "At least 30% of your password must be in the Wingdings font",
    28: "Your password must include this color in hex",
    29: "All Roman numerals must be in Times New Roman",
    30: "The font size of every digit must be equal to its square",
    31: "Every instance of the same letter must have a different font size",
    32: "Your password must include the length of your password",
    33: "The length of your password must be a prime number",
    34: "This rule is skipped!",
    35: "Your password must include the current time"
}